### ISSUE TITLE
Your code is not DRY

### ISSUE THREAD

**Issue by unicodeveloper** [andela-eosuagwu/Candy#6]
public $db_host;
    public $db_name;
    public $db_user;
    public $database;
    public $db_password;

I see this declarations in about three files Setup, DatabaseDriver and in Connect. Thats too much.

Eliminate anything that has to do with Driver, thats just unecessary code. 

Let one class or file take care of getting the environment variables and setting it, then you can have another file that does the connection with PDO . That file could even inherit from the file that sets the environment variables, so those variables could be passed easily to make a PDO connection with the database.

**Comment by emeka-osuagwu** [comment]
Fixed
